applications:
  keds:
    container_profile: HIGH_MEMORY
    source:
      root: "keds"

    type: "composable:26.05"

    stack:
      runtimes:
        - "php@8.4":
            extensions:
              - redis
      packages:
        - frankenphp
        - php84Packages.composer
        - wp-cli

    hooks:
      build: |
        set -e
        composer install --no-dev --prefer-dist --optimize-autoloader --no-progress --no-interaction
      deploy: |
        set -e
        bash scripts/deploy.sh

    relationships:
      database: "kedsdb:mysql"
      rediscache: "redis:redis"

    web:
      upstream:
        socket_family: tcp
      commands:
        start: "frankenphp run --config Caddyfile"

    mounts:
      "wordpress/wp-content/cache":
        source: storage
        source_path: "cache"
      "wordpress/wp-content/uploads":
        source: storage
        source_path: "uploads"

    crons:
      wp-cron:
        spec: "*/5 * * * *"
        cmd: "cd wordpress && wp cron event run --due-now"

services:
  kedsdb:
    type: mariadb:11.8

  redis:
    type: redis:8.0

routes:
  "https://{default}/":
    type: upstream
    upstream: "keds:http"
    cache:
      enabled: true
      cookies:
        - "/^wordpress_logged_in_/"
        - "/^wordpress_sec_/"
        - "wordpress_test_cookie"
        - "/^wp-settings-/"
        - "/^wp-postpass/"
